language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - sudo apt-get -y install `apt-cache search php | grep imagick | sed 's/ .*//'`
  - composer --prefer-source install

script: vendor/bin/phpunit --coverage-text --verbose
