language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - yum -y install php-pear ImageMagick* gcc
  - printf "\n" | pecl install imagick
  - composer --prefer-source install

script: vendor/bin/phpunit --coverage-text --verbose
