language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - php-pear
      
install:
  - printf "\n" | pecl install imagick
  - composer --prefer-source install

script: vendor/bin/phpunit --coverage-text --verbose
